### ISSUE TITLE
Portal files output needs new line (meta_mutations_extended.txt)

### ISSUE THREAD

**Issue by timosong** [mskcc/pluto-cwl#65]
The meta_mutations_extended.txt file needs the following line added in: namespaces: ASCN
https://docs.cbioportal.org/5.1-data-loading/data-loading/file-formats#example-10

Example:
`meta_mutations_extended.txt`
cancer_study_identifier: set_ldiaz
data_filename: data_mutations_extended.txt
datatype: MAF
genetic_alteration_type: MUTATION_EXTENDED
profile_description: Mutation data
profile_name: Mutations
show_profile_in_analysis_tab: true
stable_id: mutations
**namespaces: ASCN**

**Comment by stevekm** [comment]
this is merged, should be included with the next release

**Comment by stevekm** [comment]
I think this is fixed now
